import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import {z} from 'zod';
import rateLimit, { ipKeyGenerator } from 'express-rate-limit';
import {q,pool} from './db/pool.js';
import {AuthRequest,requireAuth,requireRole,signAccess,signRefresh} from './middleware/auth.js';
import {errorHandler} from './middleware/error.js';
dotenv.config();
const app=express();
app.use(cors());
app.use(express.json({limit:'2mb'}));
app.use('/api/v1/auth',rateLimit({windowMs:60000,max:10}));
app.use(
  '/api/v1/ai',
  rateLimit({
    windowMs: 60000,
    max: 20,
    keyGenerator: (req: any) =>
      req.user?.id || ipKeyGenerator(req.ip),
  }),
);
app.get('/health',async(_req,res)=>{
    try{
        await q('SELECT 1');
        res.json({status:'ok',service:'vertexlearn-core'})
    }
    catch{
        res.status(503).json({status:'degraded'})
    }});
app.post('/api/v1/auth/register',async(req,res,next)=>{try{const b=z.object({full_name:z.string().min(2).max(150),email:z.email(),password:z.string().min(8)}).parse(req.body);const hash=await bcrypt.hash(b.password,12);const u=(await q<any>('INSERT INTO users(full_name,email,password_hash,role) VALUES($1,$2,$3,\'student\') RETURNING id,full_name,email,role',[b.full_name,b.email.toLowerCase(),hash]))[0];res.status(201).json({access_token:signAccess(u),refresh_token:signRefresh(u),user:u})}catch(e:any){next(e)}});
app.post('/api/v1/auth/login',async(req,res,next)=>{try{const b=z.object({email:z.email(),password:z.string()}).parse(req.body);const u=(await q<any>('SELECT * FROM users WHERE email=$1',[b.email.toLowerCase()]))[0];if(!u||!u.is_active||!(await bcrypt.compare(b.password,u.password_hash)))return res.status(401).json({error:{code:'INVALID_CREDENTIALS',message:'Email or password is incorrect'}});const user={id:u.id,full_name:u.full_name,email:u.email,role:u.role};res.json({access_token:signAccess(user),refresh_token:signRefresh(user),user})}catch(e){next(e)}});
app.get('/api/v1/auth/me',requireAuth,async(req:AuthRequest,res,next)=>{try{res.json((await q<any>('SELECT id,full_name,email,role,avatar_url,created_at FROM users WHERE id=$1',[req.user!.id]))[0])}catch(e){next(e)}});
app.get('/api/v1/courses',async(req,res,next)=>{try{const {q:term,category,difficulty}=req.query;const rows=await q<any>(`SELECT c.id,c.title,c.description,c.category,c.difficulty,c.thumbnail_url,c.price,c.rating,c.status,u.full_name instructor FROM courses c JOIN users u ON u.id=c.instructor_id WHERE c.status='approved' AND ($1::text IS NULL OR c.title ILIKE '%'||$1||'%' OR c.description ILIKE '%'||$1||'%') AND ($2::text IS NULL OR c.category=$2) AND ($3::text IS NULL OR c.difficulty=$3) ORDER BY c.created_at DESC`,[term||null,category||null,difficulty||null]);res.json(rows)}catch(e){next(e)}});
app.get('/api/v1/courses/:id',async(req,res,next)=>{try{const c=(await q<any>('SELECT c.*,u.full_name instructor FROM courses c JOIN users u ON u.id=c.instructor_id WHERE c.id=$1',[req.params.id]))[0];if(!c)return res.status(404).json({error:{code:'NOT_FOUND',message:'Course not found'}});c.modules=await q<any>('SELECT * FROM modules WHERE course_id=$1 ORDER BY order_index',[c.id]);for(const m of c.modules)m.lectures=await q<any>('SELECT id,title,video_url,duration_seconds,order_index FROM lectures WHERE module_id=$1 ORDER BY order_index',[m.id]);res.json(c)}catch(e){next(e)}});
app.post('/api/v1/courses/:id/enroll',requireAuth,requireRole('student'),async(req:AuthRequest,res,next)=>{try{await q('INSERT INTO enrollments(user_id,course_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user!.id,req.params.id]);res.status(201).json({message:'Enrolled successfully'})}catch(e){next(e)}});
app.get('/api/v1/enrollments/me',requireAuth,async(req:AuthRequest,res,next)=>{try{res.json(await q(`SELECT e.*,c.title,c.description,c.thumbnail_url FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE e.user_id=$1 ORDER BY e.enrolled_at DESC`,[req.user!.id]))}catch(e){next(e)}});
app.post('/api/v1/courses',requireAuth,requireRole('instructor','admin'),async(req:AuthRequest,res,next)=>{try{const b=z.object({title:z.string().min(3),description:z.string().min(10),category:z.string(),difficulty:z.enum(['beginner','intermediate','advanced']),price:z.number().nonnegative().default(0)}).parse(req.body);const c=(await q<any>('INSERT INTO courses(instructor_id,title,description,category,difficulty,price,status) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[req.user!.id,b.title,b.description,b.category,b.difficulty,b.price,req.user!.role==='admin'?'approved':'pending']))[0];res.status(201).json(c)}catch(e){next(e)}});
app.post('/api/v1/courses/:id/modules',requireAuth,requireRole('instructor','admin'),async(req:AuthRequest,res,next)=>{try{const b=z.object({title:z.string().min(2),order_index:z.number().int().positive()}).parse(req.body);res.status(201).json((await q<any>('INSERT INTO modules(course_id,title,order_index) VALUES($1,$2,$3) RETURNING *',[req.params.id,b.title,b.order_index]))[0])}catch(e){next(e)}});
app.post('/api/v1/modules/:id/lectures',requireAuth,requireRole('instructor','admin'),async(req,res,next)=>{try{const b=z.object({title:z.string(),transcript:z.string().optional(),video_url:z.string().optional(),duration_seconds:z.number().int().nonnegative().default(0),order_index:z.number().int().positive()}).parse(req.body);res.status(201).json((await q<any>('INSERT INTO lectures(module_id,title,transcript,video_url,duration_seconds,order_index) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[req.params.id,b.title,b.transcript||'',b.video_url||'',b.duration_seconds,b.order_index]))[0])}catch(e){next(e)}});
app.post('/api/v1/lectures/:id/progress',requireAuth,requireRole('student'),async(req:AuthRequest,res,next)=>{try{const b=z.object({watched_seconds:z.number().int().nonnegative(),completed:z.boolean().default(false)}).parse(req.body);const e=(await q<any>('SELECT e.id FROM enrollments e JOIN modules m ON m.course_id=e.course_id JOIN lectures l ON l.module_id=m.id WHERE e.user_id=$1 AND l.id=$2',[req.user!.id,req.params.id]))[0];if(!e)return res.status(403).json({error:{code:'NOT_ENROLLED',message:'Enroll in the course first'}});await q('INSERT INTO lecture_progress(enrollment_id,lecture_id,watched_seconds,completed) VALUES($1,$2,$3,$4) ON CONFLICT(enrollment_id,lecture_id) DO UPDATE SET watched_seconds=EXCLUDED.watched_seconds,completed=EXCLUDED.completed,last_watched_at=now()',[e.id,req.params.id,b.watched_seconds,b.completed]);await q(`UPDATE enrollments SET progress_percent=(SELECT COALESCE(ROUND(100.0*SUM(CASE WHEN lp.completed THEN 1 ELSE 0 END)/NULLIF(COUNT(l.id),0),2),0) FROM lectures l JOIN modules m ON m.id=l.module_id JOIN courses c ON c.id=m.course_id LEFT JOIN lecture_progress lp ON lp.lecture_id=l.id AND lp.enrollment_id=$1 WHERE c.id=(SELECT m2.course_id FROM modules m2 JOIN lectures l2 ON l2.module_id=m2.id WHERE l2.id=$2)) WHERE id=$1`,[e.id,req.params.id]);res.json({message:'Progress updated'})}catch(e){next(e)}});
app.post('/api/v1/quizzes',requireAuth,requireRole('instructor','admin'),async(req,res,next)=>{try{const b=z.object({module_id:z.uuid(),title:z.string(),is_ai_generated:z.boolean().default(false),questions:z.array(z.object({question_text:z.string(),question_type:z.enum(['mcq','multi_select','short_answer']),options:z.array(z.object({option_text:z.string(),is_correct:z.boolean()})).default([])}))}).parse(req.body);const quiz=(await q<any>('INSERT INTO quizzes(module_id,title,is_ai_generated) VALUES($1,$2,$3) RETURNING *',[b.module_id,b.title,b.is_ai_generated]))[0];for(const [i,x] of b.questions.entries()){const qq=(await q<any>('INSERT INTO quiz_questions(quiz_id,question_text,question_type,order_index) VALUES($1,$2,$3,$4) RETURNING id',[quiz.id,x.question_text,x.question_type,i+1]))[0];for(const o of x.options)await q('INSERT INTO quiz_options(question_id,option_text,is_correct) VALUES($1,$2,$3)',[qq.id,o.option_text,o.is_correct]);}res.status(201).json(quiz)}catch(e){next(e)}});
app.get('/api/v1/quizzes/:id',requireAuth,async(req,res,next)=>{try{const quiz=(await q<any>('SELECT * FROM quizzes WHERE id=$1',[req.params.id]))[0];quiz.questions=await q<any>('SELECT id,question_text,question_type,order_index FROM quiz_questions WHERE quiz_id=$1 ORDER BY order_index',[quiz.id]);for(const x of quiz.questions)x.options=await q<any>('SELECT id,option_text FROM quiz_options WHERE question_id=$1',[x.id]);res.json(quiz)}catch(e){next(e)}});
app.post('/api/v1/quizzes/:id/attempt',requireAuth,requireRole('student'),async(req:AuthRequest,res,next)=>{try{const a=(await q<any>('INSERT INTO quiz_attempts(quiz_id,user_id) VALUES($1,$2) RETURNING *',[req.params.id,req.user!.id]))[0];res.status(201).json(a)}catch(e){next(e)}});
app.post('/api/v1/attempts/:id/submit',requireAuth,requireRole('student'),async(req:AuthRequest,res,next)=>{try{const b=z.object({answers:z.array(z.object({question_id:z.uuid(),selected_option_ids:z.array(z.uuid()).default([]),text_answer:z.string().optional()}))}).parse(req.body);const attempt=(await q<any>('SELECT * FROM quiz_attempts WHERE id=$1 AND user_id=$2',[req.params.id,req.user!.id]))[0];if(!attempt)return res.status(404).json({error:{code:'NOT_FOUND',message:'Attempt not found'}});let correct=0;const total=(await q<any>('SELECT count(*)::int n FROM quiz_questions WHERE quiz_id=$1',[attempt.quiz_id]))[0].n;for(const a of b.answers){const right=(await q<any>('SELECT id FROM quiz_options WHERE question_id=$1 AND is_correct=true ORDER BY id',[a.question_id])).map(x=>x.id);const ok=a.selected_option_ids.length===right.length&&a.selected_option_ids.every(id=>right.includes(id));if(ok)correct++;await q('INSERT INTO quiz_answers(attempt_id,question_id,selected_option_ids,text_answer,is_correct) VALUES($1,$2,$3,$4,$5)',[attempt.id,a.question_id,a.selected_option_ids,a.text_answer||null,ok]);}const score=total?Math.round(correct/total*100):0;await q('UPDATE quiz_attempts SET score=$1,submitted_at=now() WHERE id=$2',[score,attempt.id]);res.json({score,correct,total})}catch(e){next(e)}});
async function aiProxy(path:string, body:any){const r=await fetch(`${process.env.AI_SERVICE_URL||'http://ai-service:8001'}${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();return {status:r.status,data};}
app.post('/api/v1/ai/chat',requireAuth,async(req,res,next)=>{try{const x=await aiProxy('/ai/chat',req.body);res.status(x.status).json(x.data)}catch(e){next(e)}});
app.post('/api/v1/ai/summarize',requireAuth,requireRole('instructor','admin'),async(req,res,next)=>{try{const x=await aiProxy('/ai/summarize',req.body);res.status(x.status).json(x.data)}catch(e){next(e)}});
app.post('/api/v1/ai/generate-quiz',requireAuth,requireRole('instructor','admin'),async(req,res,next)=>{try{const x=await aiProxy('/ai/generate-quiz',req.body);res.status(x.status).json(x.data)}catch(e){next(e)}});
app.post('/api/v1/ai/flashcards',requireAuth,async(req,res,next)=>{try{const x=await aiProxy('/ai/flashcards',req.body);res.status(x.status).json(x.data)}catch(e){next(e)}});
app.post('/api/v1/ai/study-plan',requireAuth,async(req,res,next)=>{try{const x=await aiProxy('/ai/study-plan',req.body);res.status(x.status).json(x.data)}catch(e){next(e)}});
app.get('/api/v1/instructor/analytics',requireAuth,requireRole('instructor','admin'),async(req:AuthRequest,res,next)=>{try{const courses=await q(`SELECT c.id,c.title,count(distinct e.id)::int enrollments,coalesce(avg(qa.score),0)::numeric(5,2) avg_quiz_score FROM courses c LEFT JOIN enrollments e ON e.course_id=c.id LEFT JOIN quizzes qz ON qz.module_id IN (SELECT id FROM modules WHERE course_id=c.id) LEFT JOIN quiz_attempts qa ON qa.quiz_id=qz.id WHERE c.instructor_id=$1 GROUP BY c.id,c.title ORDER BY enrollments DESC`,[req.user!.id]);res.json({courses})}catch(e){next(e)}});
app.get('/api/v1/admin/courses/pending',requireAuth,requireRole('admin'),async(_req,res,next)=>{try{res.json(await q(`SELECT c.*,u.full_name instructor FROM courses c JOIN users u ON u.id=c.instructor_id WHERE c.status='pending' ORDER BY c.created_at`))}catch(e){next(e)}});
app.post('/api/v1/admin/courses/:id/approve',requireAuth,requireRole('admin'),async(req:AuthRequest,res,next)=>{try{const b=z.object({decision:z.enum(['approved','rejected']),comment:z.string().optional()}).parse(req.body);await q('UPDATE courses SET status=$1 WHERE id=$2',[b.decision,req.params.id]);await q('INSERT INTO course_approvals(course_id,reviewed_by,decision,comment) VALUES($1,$2,$3,$4)',[req.params.id,req.user!.id,b.decision,b.comment||null]);res.json({message:`Course ${b.decision}`})}catch(e){next(e)}});
app.get('/api/v1/admin/analytics/overview',requireAuth,requireRole('admin'),async(_req,res,next)=>{try{const [users,courses,enrollments,completion,revenue]=await Promise.all([q<any>('SELECT count(*)::int n FROM users'),q<any>('SELECT count(*)::int n FROM courses'),q<any>('SELECT count(*)::int n FROM enrollments'),q<any>('SELECT coalesce(avg(progress_percent),0)::numeric(5,2) n FROM enrollments'),q<any>('SELECT coalesce(sum(amount),0)::numeric(10,2) n FROM payments WHERE status=\'success\'')]);res.json({users:users[0].n,courses:courses[0].n,enrollments:enrollments[0].n,completion_rate:completion[0].n,revenue:revenue[0].n})}catch(e){next(e)}});
app.use(errorHandler);app.listen(8000,()=>console.log('Core LMS API listening on 8000'));
